### ISSUE TITLE
Fix animation on Nexus phones

### ISSUE THREAD

**Issue by Kadrian** [Kadrian/beer-tinder-app#2]
As we've seen yesterday, the animation doesn't work properly on chrome on a Nexus phone. @dahoo ?

**Comment by johannesjasper** [comment]
Might be Android in general, did not work on my Stock AOSP Motorola either.

**Comment by dahoo** [comment]
On my Stock Android Nexus 5 it doesn't work with Chrome, but with Firefox. It seem like a general Chrome/Android issue: https://github.com/jquery/jquery-mobile/issues/5534

**Comment by dahoo** [comment]
This demo is buggy in both browsers (less in Firefox though): http://view.jquerymobile.com/master/demos/swipe-page/
Maybe we can go for a CSS3 solution? http://smotko.si/tinder-css/

**Comment by dahoo** [comment]
This demo swipes pretty smooth: http://codepen.io/mattjburrows/pen/GFCKL

**Comment by Kadrian** [comment]
Maybe the solution could be replacing the transition on the margin with a translateX?

**Comment by dahoo** [comment]
Fixed, with d1ad3de52779013daf07272f6740edc141b664b3, the problem was the immediate `fadeOut`.
